### ISSUE TITLE
Consecutive conversions result in NullPointerException

### ISSUE THREAD

**Issue by gokberkkaraca** [royludo/cd2sbgnml#8]
By using the [compartment_closeup.xml](https://github.com/royludo/cd2sbgnml/blob/master/samples/compartment_closeup.xml) file that is provided under [samples](https://github.com/royludo/cd2sbgnml/tree/master/samples) folder, I tried converting the file from cd to sbgnml and from sbgnml to cd consecutively.

Cell Designer -> SBGNML conversion was successful.
SBGNML -> Cell Designer conversion was successful.
Cell Designer -> SBGNML conversion resulted in a NullPointerException with the following error message,

`Exception in thread "main" java.lang.NullPointerException
        at fr.curie.cd2sbgnml.xmlcdwrappers.ModelWrapper.addBasicLists(ModelWrapper.java:105)
        at fr.curie.cd2sbgnml.xmlcdwrappers.ModelWrapper.create(ModelWrapper.java:62)
        at fr.curie.cd2sbgnml.CD2SBGNML.toSbgn(CD2SBGNML.java:53)
        at fr.curie.cd2sbgnml.CD2SBGNML.convert(CD2SBGNML.java:789)
        at fr.curie.cd2sbgnml.Cd2SbgnmlScript.convert(Cd2SbgnmlScript.java:48)
        at fr.curie.cd2sbgnml.Cd2SbgnmlScript.main(Cd2SbgnmlScript.java:33)`

Because of this issue, I am not able to import the file that is exported by using cd2sbgnml library.

**Comment by royludo** [comment]
That is not surprising, chaining conversions back and forth has always lead to unpredictable behaviors. Some things cannot be converted properly, there is some degree of loss, due to the 2 formats being quite different. I thought I had put a warning about that in the wiki, but it appears I didn't. That will be added.

As for the issue itself, I'm afraid it would require some serious effort to fix it.
